### ISSUE TITLE
Can't import miditok, no module named tokenizer

### ISSUE THREAD

**Issue by fosfrancesco** [Natooz/MidiTok#50]
Hello,
I've just installed the packages. When I try to import it, I get an exception:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\fosca\anaconda3\envs\mir_research\lib\site-packages\miditok\__init__.py", line 1, in <module>
    from .tokenizations import (
  File "C:\Users\fosca\anaconda3\envs\mir_research\lib\site-packages\miditok\tokenizations\__init__.py", line 1, in <module>
    from .remi import REMI
  File "C:\Users\fosca\anaconda3\envs\mir_research\lib\site-packages\miditok\tokenizations\remi.py", line 7, in <module>
    from ..midi_tokenizer import MIDITokenizer, _in_as_seq, _out_as_complete_seq
  File "C:\Users\fosca\anaconda3\envs\mir_research\lib\site-packages\miditok\midi_tokenizer.py", line 15, in <module>
    from tokenizers import Tokenizer as TokenizerFast
ModuleNotFoundError: No module named 'tokenizers'
```

I would suggest adding this package to the requirements for automatic install, or at least write that this need to be installed.
Thank you for the great work!

**Comment by Natooz** [comment]
Hello,

Thanks for the report!
`tokenizers` is already in the requirements, but wasn't in `setup.py`. That's fixed, now, it will be applied in the next release! 👍
